// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: proto/netvisor/v1/network.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	LinkName  string `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	Mtu       uint32 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Flags     uint32 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	OperState uint32 `protobuf:"varint,5,opt,name=oper_state,json=operState,proto3" json:"oper_state,omitempty"`
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_netvisor_v1_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netvisor_v1_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_proto_netvisor_v1_network_proto_rawDescGZIP(), []int{0}
}

func (x *Interface) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Interface) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *Interface) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Interface) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Interface) GetOperState() uint32 {
	if x != nil {
		return x.OperState
	}
	return 0
}

type ListInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListInterfaceRequest) Reset() {
	*x = ListInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_netvisor_v1_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfaceRequest) ProtoMessage() {}

func (x *ListInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netvisor_v1_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfaceRequest.ProtoReflect.Descriptor instead.
func (*ListInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_netvisor_v1_network_proto_rawDescGZIP(), []int{1}
}

type ListInterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interfaces []*Interface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
}

func (x *ListInterfaceResponse) Reset() {
	*x = ListInterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_netvisor_v1_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfaceResponse) ProtoMessage() {}

func (x *ListInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_netvisor_v1_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfaceResponse.ProtoReflect.Descriptor instead.
func (*ListInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_netvisor_v1_network_proto_rawDescGZIP(), []int{2}
}

func (x *ListInterfaceResponse) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

var File_proto_netvisor_v1_network_proto protoreflect.FileDescriptor

var file_proto_netvisor_v1_network_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x74, 0x76, 0x69, 0x73, 0x6f, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x6e, 0x65, 0x74, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x85,
	0x01, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74,
	0x75, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65,
	0x74, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x32,
	0x68, 0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x56, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x21, 0x2e, 0x6e, 0x65, 0x74, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x65, 0x74, 0x76, 0x69, 0x73, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x75, 0x73, 0x68, 0x70, 0x61, 0x74,
	0x72, 0x61, 0x31, 0x31, 0x2f, 0x6e, 0x65, 0x74, 0x76, 0x69, 0x73, 0x6f, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_netvisor_v1_network_proto_rawDescOnce sync.Once
	file_proto_netvisor_v1_network_proto_rawDescData = file_proto_netvisor_v1_network_proto_rawDesc
)

func file_proto_netvisor_v1_network_proto_rawDescGZIP() []byte {
	file_proto_netvisor_v1_network_proto_rawDescOnce.Do(func() {
		file_proto_netvisor_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_netvisor_v1_network_proto_rawDescData)
	})
	return file_proto_netvisor_v1_network_proto_rawDescData
}

var file_proto_netvisor_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_netvisor_v1_network_proto_goTypes = []interface{}{
	(*Interface)(nil),             // 0: netvisor.v1.Interface
	(*ListInterfaceRequest)(nil),  // 1: netvisor.v1.ListInterfaceRequest
	(*ListInterfaceResponse)(nil), // 2: netvisor.v1.ListInterfaceResponse
}
var file_proto_netvisor_v1_network_proto_depIdxs = []int32{
	0, // 0: netvisor.v1.ListInterfaceResponse.interfaces:type_name -> netvisor.v1.Interface
	1, // 1: netvisor.v1.NetworkService.ListInterface:input_type -> netvisor.v1.ListInterfaceRequest
	2, // 2: netvisor.v1.NetworkService.ListInterface:output_type -> netvisor.v1.ListInterfaceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_netvisor_v1_network_proto_init() }
func file_proto_netvisor_v1_network_proto_init() {
	if File_proto_netvisor_v1_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_netvisor_v1_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_netvisor_v1_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_netvisor_v1_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListInterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_netvisor_v1_network_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_netvisor_v1_network_proto_goTypes,
		DependencyIndexes: file_proto_netvisor_v1_network_proto_depIdxs,
		MessageInfos:      file_proto_netvisor_v1_network_proto_msgTypes,
	}.Build()
	File_proto_netvisor_v1_network_proto = out.File
	file_proto_netvisor_v1_network_proto_rawDesc = nil
	file_proto_netvisor_v1_network_proto_goTypes = nil
	file_proto_netvisor_v1_network_proto_depIdxs = nil
}
